# Generated by Django 4.0.9 on 2023-02-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipareas',
            name='mentors',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentorship_areas',
            field=models.ManyToManyField(to='mentors.mentorshipareas'),
        ),
    ]
