# Generated by Django 4.0.9 on 2023-02-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_remove_mentorshipareas_mentors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentorship_areas',
            field=models.ManyToManyField(related_name='+', to='mentors.mentorshipareas'),
        ),
    ]
