# Generated by Django 4.0.9 on 2023-02-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_alter_mentor_mentorship_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
