# Generated by Django 4.0.9 on 2023-02-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentor_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('BOOKED', 'booked'), ('CANCELLED', 'cancelled'), ('FULFILLED', 'fulfilled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('BUSY', 'busy'), ('FREE', 'free')], default='FREE', max_length=10),
        ),
    ]
