# Generated by Django 4.0.9 on 2023-02-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_alter_appointment_status_alter_slot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notavailable',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='DaysOfWeek',
        ),
        migrations.DeleteModel(
            name='NotAvailable',
        ),
    ]
