# Generated by Django 4.0.9 on 2023-02-16 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1990, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
