# Generated by Django 4.0.9 on 2023-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_expertise_created_at_expertise_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(to='users.expertise'),
        ),
    ]
