# Generated by Django 4.0.9 on 2023-02-16 12:33

import adplist.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_groups_user_is_active_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', adplist.users.models.CustomUserManager()),
            ],
        ),
    ]
